title = "ncolesummers.com"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = "This site was created using bartholomew, the micro-CMS delivered as a WASM module and served by WAGI.  While WASM has been speeding up JS for some time now, server-side WASM is still experimental."

[extra]
copyright = "N. Cole Summers 2022"
github = "https://github.com/ncolesummers"
twitter = "https://twitter.com/ncolesummers"
instagram = "https://instagram.com/ncolesummers"